### ISSUE TITLE
GettingStarted sample code does not compile

### ISSUE THREAD

**Issue by ochafik** [ochafik/ScalaCL#16]
_From @mslinn on January 10, 2012 21:27_

Here is my build.sbt:

````
name := "ScalaClTest"

version := "0.1"

scalaVersion := "2.9.1"

autoCompilerPlugins := true

scalacOptions ++= Seq("-deprecation")

addCompilerPlugin("com.nativelibs4java" % "scalacl-compiler-plugin" % "0.2")

resolvers ++= Seq(
  "Sonatype OSS Snapshots" at "http://oss.sonatype.org/content/groups/public/",
  "NativeLibs4Java"        at "http://nativelibs4java.sourceforge.net/maven/",
  "Typesafe Snapshots"     at "http://repo.typesafe.com/typesafe/snapshots",
  "Typesafe Releases"      at "http://repo.typesafe.com/typesafe/releases",
  "Scala-Tools Snapshots"  at "http://scala-tools.org/repo-snapshots",
  "Scala Tools Releases"   at "http://scala-tools.org/repo-releases",
  "Sonatype"               at "http://nexus.scala-tools.org/content/repositories/public"
)

libraryDependencies ++= Seq(
  "com.nativelibs4java" %  "scalacl"   % "latest.integration" % "compile" withSources(),
  "org.scalatest"       %% "scalatest" % "latest.integration" % "test"    withSources()
)
````

I get two errors when compiling the [GettingStarted sample code](http://code.google.com/p/scalacl/wiki/GettingStarted):
````
[error] E:\work\experiments\scala\scalaclTest\src\main\scala\Test.scala:6: value best is not a member of object scalacl.Context
[error]  Note: implicit value context is not applicable here because it comes after the application point and it lacks an explicit result type
[error]     implicit val context = Context.best // prefer CPUs ? use Context.best(CPU)
[error]                                    ^
[error] E:\work\experiments\scala\scalaclTest\src\main\scala\Test.scala:7: value cl is not a member of scala.collection.immutable.Range
[error]     val rng = (100 until 100000).cl // transform the Range into a CLIntRange
````

_Copied from original issue: ochafik/nativelibs4java#229_

**Comment by ochafik** [comment]
Hi mslinn,

Unfortunately ScalaCL 0.2 was compiled against Scala 2.8.x and won't work with Scala 2.9.x.
You can either use `scalaVersion := "2.8.2"` or try using version 0.3-SNAPSHOT of the plugin (anyway I believe you're implicitly using version 0.3-SNAPSHOT of the runtime ScalaCL Collections library with "latest.integration" : you should use the same version for the plugin and the library, since they're tightly coupled).

Cheers

**Comment by ochafik** [comment]
_From @mslinn on January 10, 2012 21:59_

Changing build.sbt worked:

````
scalaVersion := "2.8.2"
````

... but I don't want to use the older version of Scala compiler. Changing the library dependency to:

````
  "com.nativelibs4java" %  "scalacl"   % "0.3-SNAPSHOT" % "compile" withSources(),
````
Gave me this:

````
[warn] [scalacl] Test.scala:9 An unexpected error occurred while attempting an optimization
[warn] [scalacl] Test.scala:9   Attempted optimization : 'associated equivalent OpenCL source to scalacl.CLIndexedSeq[(Int, Int)].map's function argument.'
[warn] [scalacl] Test.scala:9   You can skip this line with the following environment variable :
[warn] [scalacl] Test.scala:9     SCALACL_SKIP=Test.scala:9
[warn] [scalacl] Test.scala:9   To display the error and help debug the ScalaCL compiler plugin, please set the following environment variable :
[warn] [scalacl] Test.scala:9     SCALACL_TRACE=1
[warn] [scalacl] Test.scala:9   You can help by filing bugs here (with [ScalaCLPlugin] in the title) :
[warn] [scalacl] Test.scala:9     http://code.google.com/p/nativelibs4java/issues/entry
[scalacl] Test.scala:9 An unexpected error occurred while attempting an optimization
[scalacl] Test.scala:9   Attempted optimization : 'associated equivalent OpenCL source to scalacl.CLIndexedSeq[(Int, Int)].map's function argument.'
[scalacl] Test.scala:9   You can skip this line with the following environment variable :
[scalacl] Test.scala:9     SCALACL_SKIP=Test.scala:9
[scalacl] Test.scala:9   To display the error and help debug the ScalaCL compiler plugin, please set the following environment variable :
[scalacl] Test.scala:9     SCALACL_TRACE=1
[scalacl] Test.scala:9   You can help by filing bugs here (with [ScalaCLPlugin] in the title) :
[scalacl] Test.scala:9     http://code.google.com/p/nativelibs4java/issues/entry
[warn] [scalacl] Test.scala:9 An unexpected error occurred while attempting an optimization
[warn] [scalacl] Test.scala:9   Attempted optimization : 'associated equivalent OpenCL source to scalacl.CLRange.map's function argument.'
[warn] [scalacl] Test.scala:9   You can skip this line with the following environment variable :
[warn] [scalacl] Test.scala:9     SCALACL_SKIP=Test.scala:9
[warn] [scalacl] Test.scala:9   To display the error and help debug the ScalaCL compiler plugin, please set the following environment variable :
[warn] [scalacl] Test.scala:9     SCALACL_TRACE=1
[warn] [scalacl] Test.scala:9   You can help by filing bugs here (with [ScalaCLPlugin] in the title) :
[warn] [scalacl] Test.scala:9     http://code.google.com/p/nativelibs4java/issues/entry
[scalacl] Test.scala:9 An unexpected error occurred while attempting an optimization
[scalacl] Test.scala:9   Attempted optimization : 'associated equivalent OpenCL source to scalacl.CLRange.map's function argument.'
[scalacl] Test.scala:9   You can skip this line with the following environment variable :
[scalacl] Test.scala:9     SCALACL_SKIP=Test.scala:9
[scalacl] Test.scala:9   To display the error and help debug the ScalaCL compiler plugin, please set the following environment variable :
[scalacl] Test.scala:9     SCALACL_TRACE=1
[scalacl] Test.scala:9   You can help by filing bugs here (with [ScalaCLPlugin] in the title) :
[scalacl] Test.scala:9     http://code.google.com/p/nativelibs4java/issues/entry
````
Looks like there are too many issues for this package right now. I'll go back to lurking and will try again when it seems a bit more mature.

Mike

**Comment by ochafik** [comment]
Yes, sorry about this, version 0.3-SNAPSHOT is a mess right now (just split into two projects + in the middle of repository migration). Should hopefully be settled soon, I'll keep you posted here.

Cheers

**Comment by barrybecker4** [comment]
Is it still a mess? I don't seen any activity on this project since this post was written. Is there another alternative out there for using CL with scala?
